<a href="https://colab.research.google.com/github/karishmanetturi/karishma/blob/main/Deep_learning_L1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# Scalar example
scalar = np.array(5)
print("Scalar value:", scalar)

Scalar value: 5


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return 0
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return 0
    return 1

# Create dataset
X = np.arange(2, 1001)
y = np.array([is_prime(x) for x in X])

# Define the model
model = Sequential([
    Dense(16, input_dim=1, activation='relu'),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X, y, epochs=50, batch_size=10)

# Evaluate the model
loss, accuracy = model.evaluate(X, y)
print(f"Model accuracy: {accuracy * 100:.2f}%")

# Predict if a new number is prime
number = 29
prediction = model.predict([number])
print(f"Probability that {number} is prime: {prediction[0][0]:.2f}")


Epoch 1/50


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6972 - loss: 1.3221
Epoch 2/50
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8039 - loss: 0.6127
Epoch 3/50
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.6309
Epoch 4/50
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7807 - loss: 0.6227
Epoch 5/50
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7739 - loss: 0.6522
Epoch 6/50
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7921 - loss: 0.6837
Epoch 7/50
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7915 - loss: 0.6856
Epoch 8/50
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8150 - loss: 0.5398
Epoch 9/50
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7903 - loss: 0.5877
Epoch 10/50
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8222 - loss: 0.5603
Epoch 11/50
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8177 - loss: 0.6268
Epoch 12/50
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy

ValueError: Unrecognized data type: x=[29] (of type <class 'list'>)

In [ ]:
import numpy as np

# Scalar example
scalar = np.array(5)
print("Scalar value:", scalar)

# Vector example
vector = np.array([1, 2, 3])
print("Vector values:", vector)

# 2D Tensor (Matrix) example
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Tensor (Matrix):\n", matrix)

# 3D Tensor example
tensor_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Tensor:\n", tensor_3d)

# 4D Tensor example
tensor_4d = np.random.rand(2, 3, 4, 5)
print("Shape of 4D Tensor:", tensor_4d.shape)


Scalar value: 5
Vector values: [1 2 3]
2D Tensor (Matrix):
 [[1 2 3]
 [4 5 6]]
3D Tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of 4D Tensor: (2, 3, 4, 5)


In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

# Step 1: Generate Training Data
def generate_data(num_samples):
    x1 = np.random.randint(0, 100, size=num_samples)
    x2 = np.random.randint(0, 100, size=num_samples)
    y = x1 + x2
    return np.vstack((x1, x2)).T, y

num_samples = 10000
X, y = generate_data(num_samples)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 2: Define the Model
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))  # Input layer with 2 inputs
model.add(Dense(5, activation='relu'))  # Hidden layer
model.add(Dense(1))  # Output layer

# Step 3: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error')

# Step 4: Train the Model
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2)

# Step 5: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')

# Make a prediction
sample_input = np.array([[23, 45]])  # Example input
predicted_sum = model.predict(sample_input)
print(f'Predicted Sum: {predicted_sum[0][0]}')


KeyboardInterrupt: 

https://colab.research.google.com/drive/1ncbDP-JQA-yAscsCOHy8MSSba2hGiEgu#scrollTo=W_B-u_70MhlD&line=1&uniqifier=1

https://colab.research.google.com/drive/1ncbDP-JQA-yAscsCOHy8MSSba2hGiEgu#scrollTo=W_B-u_70MhlD&line=1&uniqifier=1

https://colab.research.google.com/drive/1ncbDP-JQA-yAscsCOHy8MSSba2hGiEgu#scrollTo=W_B-u_70MhlD&line=1&uniqifier=1

https://github.com/223t1a3105/colab-saved-data/blob/main/Deep_Learning_Lab_1(27_07_24).ipynb

https://github.com/karishmanetturi/karishma/blob/main/deep%20learning

https://github.com/223t1a3155/reddy/blob/main/DL%20Lab-.1(27-07-24)

https://github.com/UmaEdiga04/addition-of-matrices/commit/dd98a3e7d880ed654d37a1efc62d1e571934afca

https://github.com/ZoyaMehek/ZoyaMehek/commit/60b281b29c2079c9f646f5af69a9aac357286504


https://github.com/raeesa1718/deeplearning/commit/29359f060d08ab81a0f1053cfaabed5287e54c45

https://github.com/J-Sowmya-18/Deep-Learning-lab/blob/main/lab3.ipynb
(223t1a3118)



https://github.com/KuruvaPoojitha11/Deep-Learning-lab-program/blob/main/Deep_Learning_lab1.ipynb (223T1A3123)

https://github.com/Meghana12c/Deep-Learning-Lab-Programs/blob/main/Deep_Learning_lab1.ipynb  (223T1A3108)



https://github.com/pallejahnavireddy14/google-colab-data/blob/main/google%20colab%201 (223T1A3132)


https://github.com/VyzaBhavana/Bhavana/commit/315d2ba228e172e49936099cc6ccbad9bee810b6 (223T1A3157)

https://github.com/223t1a3127/Sree/blob/main/DL.ipynb (223T1A3127)

https://github.com/TMeghana54/meghana/blob/main/Lab1_Deep_Learning.ipynb (223T1A3154)

https://github.com/Mythili134/deep/blob/main/deep_learning.ipynb (223T1A3134)

https://github.com/Vijaya-116/deep-learning-lab(223t1a3116)

https://github.com/Gayathri-achari/DL-COLAB

https://github.com/SUSHMA750/sushma

https://github.com/Kavyayadav166
